/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheLanguageControl: typeof import('./components/TheLanguageControl.vue')['default']
    TheSettings: typeof import('./components/TheSettings.vue')['default']
    TheSettingsWrapper: typeof import('./components/TheSettingsWrapper.vue')['default']
    TheToolHelp: typeof import('./components/TheToolHelp.vue')['default']
  }
}
